Repository pixelsdb/pixels, pull requests merged in 2022-03, with the labels that each got.

#200 [Issue #196]: fix DecimalColumnVector and use decimal in TPC-H schema.
  pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DecimalColumnVector.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/vector/TestDecimalColumnVector.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/PixelsConsumer.java
  scripts/sql/tpch_schema.sql
Labels: bug

#201 [Issue #192]: support multi-thread compaction.
  README.md
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/Main.java
Labels: enhancement

#202 [Issue #192]: refine compact, S3, PixelsCompactor, and support multi-thread copying.
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/S3InputStream.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/S3OutputStream.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/S3.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/compactor/PixelsCompactor.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/Main.java
  pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsSplitManager.java
Labels: enhancement

#206 [Issue #205]: fix integer overflow in request merging.
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Scheduler.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/SortMergeScheduler.java
  pixels-common/src/main/resources/pixels.properties
Labels: bug

#211 [Issue #208]: fix column statistics for decimal.
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/StatsRecorder.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/DecimalColumnWriter.java
  pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsPageSource.java
  pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsRecordCursor.java
  pixels-presto/src/main/java/io/pixelsdb/pixels/presto/impl/PixelsTupleDomainPredicate.java
  pixels-presto/src/test/java/io/pixelsdb/pixels/presto/impl/TestPixelsPredicate.java
Labels: bug

#212 [Issue #207]: fix the data type metadata in the file footer.
  pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/StatsRecorder.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestPixelsReaderBasic.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/Main.java
  pixels-load/src/test/java/io/pixelsdb/pixels/load/TestPixelsCore.java
  pixels-presto/src/main/java/io/pixelsdb/pixels/presto/impl/PixelsTupleDomainPredicate.java
Labels: bug

#213 [Issue #209]: clean code.
  pixels-load/README.md
  pixels-load/pom.xml
  pixels-load/src/main/java/io/pixelsdb/pixels/load/Config.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/Consumer.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/ConsumerGenerator.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/Main.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/ORCConsumer.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/PixelsConsumer.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/PixelsProducer.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/single/Loader.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/single/Main.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/single/ORCLoader.java
  pixels-load/src/main/java/io/pixelsdb/pixels/load/single/PixelsLoader.java
  pixels-load/src/test/java/io/pixelsdb/pixels/load/TestPixelsWriter.java
Labels: enhancement

#215 [Issue #189]: support folders on S3.
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Storage.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalS3Reader.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/HDFS.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/LocalFS.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/S3.java
  pixels-common/src/test/java/io/pixelsdb/pixels/common/TestS3.java
Labels: enhancement

#216 [Issue #189]: revise docs and scripts.
  README.md
  scripts/sql/tpch_layouts.sql
Labels: documentation

#221 [Issue #220] revise license, readme, and pom.
  LICENSE
  NOTICE
  README.md
  pom.xml
Labels: documentation, enhancement

#223 [Issue #222]: disable mock file locations for storage systems that do not provide data locality.
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/AbsoluteBalancer.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/Balancer.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/ReplicaBalancer.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Location.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Storage.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/HDFS.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/LocalFS.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/S3.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
Labels: enhancement

#230 [Issue #224]: clean and refine cache key and cache entry implementation.
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/CacheLogger.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/ColumnletId.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/ColumnletSeq.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheEntry.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheIdx.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheKey.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheKeyUtil.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheReader.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsRadix.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/mq/Message.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/mq/SharedMQ.java
  pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPixelsRadix.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/error/ErrorCode.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalLocalReader.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalS3Reader.java
Labels: enhancement

#232 [Issue #231]: update docs and comments.
  README.md
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/StorageFactory.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
Labels: enhancement

#234 [Issue #225]: upgrade to Hadoop 3.3.1 and clean dependencies.
  NOTICE
  pixels-common/pom.xml
  pixels-common/src/main/java/io/pixelsdb/pixels/common/lock/EtcdMutex.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/lock/LockInternals.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/StorageFactory.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/StringUtil.java
  pixels-common/src/test/java/io/pixelsdb/pixels/common/TestHDFS.java
  pixels-core/pom.xml
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/DynamicByteArray.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/EncodingUtils.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/StringRedBlackTree.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/Text.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/TestCacheContent.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestPixelsWriter.java
  pixels-daemon/pom.xml
  pixels-lambda/pom.xml
  pixels-load/pom.xml
  pixels-tools/pom.xml
  pom.xml
Labels: enhancement

#235 [Issue #231]: enable storage schemes in configuration.
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/StorageFactory.java
  pixels-common/src/main/resources/pixels.properties
Labels: enhancement

#236 [Issue #233]: fix log4j configurations.
  README.md
  pixels-cache/src/main/resources/log4j2.properties
  pixels-common/src/main/java/io/pixelsdb/pixels/common/exception/CacheException.java
  pixels-common/src/main/resources/log4j2.properties
  pixels-core/src/main/resources/log4j2.properties
  pixels-daemon/src/main/resources/log4j2.properties
  pixels-lambda/src/main/resources/log4j2.properties
  pixels-load/src/main/resources/log4j2.properties
  pixels-tools/src/main/resources/log4j2.properties
Labels: enhancement

#237 [Issue #193]: revise the README under modules.
  pixels-daemon/README.md
  pixels-load/README.md
  pixels-tools/README.md
Labels: documentation

#243 [Issue #170]: fix dependencies and logging for pixels-lambda.
  pixels-common/src/main/resources/pixels.properties
  pixels-lambda/1-update-code.sh
  pixels-lambda/2-invoke.sh
  pixels-lambda/README.md
  pixels-lambda/pom.xml
  pixels-lambda/response.json
  pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/QueryExecutor.java
  pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/Scan.java
  pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ScanWorker.java
  pixels-lambda/src/main/resources/log4j2.properties
  pixels-lambda/src/main/resources/log4j2.xml
  pixels-lambda/src/test/java/ScanTest.java
  pixels-lambda/src/test/java/WorkerTest.java
  pixels-lambda/src/test/java/io/pixelsdb/pixels/lambda/ScanWorkerTest.java
  pom.xml
Labels: enhancement

#246 [Issue #170]: implement filter.
  pixels-lambda/1-update-code.sh
  pixels-lambda/2-invoke.sh
  pixels-lambda/response.json
  pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ExprTree.java
  pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ScanWorker.java
  pixels-lambda/src/test/java/io/pixelsdb/pixels/lambda/ExprTreeTest.java
  pixels-lambda/src/test/java/io/pixelsdb/pixels/lambda/ScanScanWorkerTest.java
Labels: enhancement

#247 [Issue #170]: clean the unused files and reformat the code.
  pixels-lambda/1-update-code.sh
  pixels-lambda/2-invoke.sh
  pixels-lambda/response.json
  pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ExprTree.java
  pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ScanWorker.java
  pixels-lambda/src/test/java/io/pixelsdb/pixels/lambda/ExprTreeTest.java
  pixels-lambda/src/test/java/io/pixelsdb/pixels/lambda/ScanScanWorkerTest.java
Labels: enhancement

#248 [Issue #170]: update poms for pixels-lambda.
  pixels-lambda/pom.xml
  pom.xml
Labels: enhancement
