Repository pixelsdb/pixels, pull requests merged in 2023-03, with the labels that each got.

#406 [Issue #405] refine configuration properties.
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metrics/ReadPerfHistogram.java
  pixels-common/src/main/resources/pixels.properties
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/PixelsCoreConfig.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/DaemonMain.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metrics/MetricsServer.java
  pixels-daemon/src/test/java/io/pixelsdb/pixels/daemon/metrics/TestJsonParse.java
  pixels-daemon/src/test/java/io/pixelsdb/pixels/daemon/metrics/TestMetricServer.java
  pixels-daemon/src/test/java/io/pixelsdb/pixels/daemon/metrics/TestPrometheus.java
Labels: documentation, enhancement

#407 [Issue #405] fix comments.
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/DirectIoLib.java
Labels: documentation

#412 [Issue #408]: improve exception handling in pixels-daemon.
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/DaemonMain.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheManager.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/DiskCacheManager.java
Labels: enhancement

#413 [Issue #410] implement the REST API for SQL execution.
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/MetaDBUtil.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/QueryEngineConns.java
  pixels-common/src/main/resources/pixels.properties
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServer.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbColumnDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbLayoutDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbSchemaDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbTableDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbViewDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/rest/RestServer.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/rest/RestServerHandler.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/rest/request/CloseEngineConn.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/rest/request/ExecuteQuery.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/rest/request/OpenEngineConn.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/rest/response/QueryResult.java
  pixels-daemon/src/test/java/io/pixelsdb/pixels/daemon/rest/TestRequests.java
  pom.xml
Labels: enhancement

#415 [Issue #414] pixels reads replicated content on string column after the first row batch, when the column is not encoded.
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
Labels: bug
