Repository pixelsdb/pixels, pull requests merged in 2023-08, with the labels that each got.

#520 [Issue #519] fix wrong column chunk offsets in a multi-row-group file
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
Labels: bug

#523 [Issue #517] load single tbl file into multiple paths
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/load/PixelsConsumer.java
Labels: enhancement

#525 [Issue #524] using full path as the key in file footer cache
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
  proto/pixels.proto
Labels: bug

#526 [Issue #522] add layout configurations into the file format
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
  proto/pixels.proto
Labels: enhancement

#532 [Issue #521] support chunk aligned compact file
  pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/InvertedSplitsIndex.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/SplitPattern.java
  pixels-common/src/main/resources/pixels.properties
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/compactor/PixelsCompactor.java
Labels: bug, enhancement

#534 [Issue #531] support configurable endianness
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsPhysicalReader.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/PhysicalReader.java
  pixels-common/src/main/resources/pixels.properties
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/compactor/PixelsCompactor.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/Dictionary.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/Encoder.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/IntDecoder.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/RedBlackTree.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/RunLenByteDecoder.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/RunLenIntDecoder.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/RunLenIntEncoder.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/StringRedBlackTree.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/BinaryColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/BooleanColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ByteColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/CharColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DateColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DecimalColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DoubleColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/FloatColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/IntegerColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongDecimalColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimeColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/VarbinaryColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/VarcharColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/EncodingUtils.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/BaseColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/BinaryColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/BooleanColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/ByteColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/CharColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/ColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/DateColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/DecimalColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/DoubleColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/FloatColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/IntegerColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/LongDecimalColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/StringColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/TimeColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/TimestampColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/VarbinaryColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/VarcharColumnWriter.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestStringColumnWriter.java
  pixels-example/src/main/java/io/pixelsdb/pixels/example/core/MockPixelsReader.java
  pixels-storage/pixels-storage-gcs/src/main/java/io/pixelsdb/pixels/storage/gcs/PhysicalGCSReader.java
  pixels-storage/pixels-storage-hdfs/src/main/java/io/pixelsdb/pixels/storage/hdfs/PhysicalHDFSReader.java
  pixels-storage/pixels-storage-localfs/src/main/java/io/pixelsdb/pixels/storage/localfs/PhysicalLocalReader.java
  pixels-storage/pixels-storage-mock/src/main/java/io/pixelsdb/pixels/storage/mock/PhysicalMockReader.java
  pixels-storage/pixels-storage-redis/src/main/java/io/pixelsdb/pixels/storage/redis/PhysicalRedisReader.java
  pixels-storage/pixels-storage-s3/src/main/java/io/pixelsdb/pixels/storage/s3/AbstractS3Reader.java
  pixels-turbo/pixels-worker-vhive/README.md
  proto/pixels.proto
Labels: enhancement

#536 [Issue #535] change project version to 0.1.0
  pixels-cache/Makefile
  pixels-cache/pom.xml
  pixels-cli/pom.xml
  pixels-common/pom.xml
  pixels-core/pom.xml
  pixels-daemon/pom.xml
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/DaemonMain.java
  pixels-example/pom.xml
  pixels-executor/pom.xml
  pixels-parser/pom.xml
  pixels-planner/pom.xml
  pixels-server/pom.xml
  pixels-storage/pixels-storage-gcs/pom.xml
  pixels-storage/pixels-storage-hdfs/pom.xml
  pixels-storage/pixels-storage-localfs/pom.xml
  pixels-storage/pixels-storage-mock/pom.xml
  pixels-storage/pixels-storage-redis/pom.xml
  pixels-storage/pixels-storage-s3/pom.xml
  pixels-turbo/pixels-invoker-lambda/pom.xml
  pixels-turbo/pixels-invoker-vhive/pom.xml
  pixels-turbo/pixels-scaling-ec2/pom.xml
  pixels-turbo/pixels-worker-common/pom.xml
  pixels-turbo/pixels-worker-lambda/pom.xml
  pixels-turbo/pixels-worker-vhive/pom.xml
  pom.xml
Labels: enhancement

#537 [Issue #535] upgrade project to 0.2.0-SNAPSHOT
  pixels-cache/Makefile
  pixels-cache/pom.xml
  pixels-cli/pom.xml
  pixels-common/pom.xml
  pixels-core/pom.xml
  pixels-daemon/pom.xml
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/DaemonMain.java
  pixels-example/pom.xml
  pixels-executor/pom.xml
  pixels-parser/pom.xml
  pixels-planner/pom.xml
  pixels-server/pom.xml
  pixels-storage/pixels-storage-gcs/pom.xml
  pixels-storage/pixels-storage-hdfs/pom.xml
  pixels-storage/pixels-storage-localfs/pom.xml
  pixels-storage/pixels-storage-mock/pom.xml
  pixels-storage/pixels-storage-redis/pom.xml
  pixels-storage/pixels-storage-s3/pom.xml
  pixels-turbo/pixels-invoker-lambda/pom.xml
  pixels-turbo/pixels-invoker-vhive/pom.xml
  pixels-turbo/pixels-scaling-ec2/pom.xml
  pixels-turbo/pixels-worker-common/pom.xml
  pixels-turbo/pixels-worker-lambda/pom.xml
  pixels-turbo/pixels-worker-vhive/pom.xml
  pom.xml
Labels: enhancement

#540 Fix compilation error: move partitioned from footer to postScript
  cpp/pixels-reader/pixels-core/lib/PixelsReaderImpl.cpp
Labels: enhancement

#544 [Issue #539] replace lengths with starts for non-encoded string columns.
  cpp/README.md
  cpp/pixels-reader/pixels-core/lib/reader/StringColumnReader.cpp
  pixels-common/src/main/resources/pixels.properties
  pixels-core/pom.xml
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/DynamicIntArray.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/EncodingUtils.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/StringColumnWriter.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/TestByteBuf.java
Labels: enhancement

#550 [Issue #549] fix dependencies for slf4j
  pixels-cli/pom.xml
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/DirectIoLib.java
  pixels-daemon/pom.xml
  pixels-turbo/pixels-invoker-vhive/pom.xml
  pixels-turbo/pixels-worker-common/pom.xml
  pixels-turbo/pixels-worker-lambda/pom.xml
  pixels-turbo/pixels-worker-vhive/pom.xml
  pom.xml
Labels: enhancement

#552 [Issue #549] resolve conflict bindings between log4j and slf4j
  pixels-cli/pom.xml
  pixels-daemon/pom.xml
  pixels-example/pom.xml
  pixels-turbo/pixels-worker-lambda/pom.xml
  pixels-turbo/pixels-worker-vhive/pom.xml
  pom.xml
Labels: enhancement

#561 [Issue #538] support encoding levels and dictionary encoding without cascading RLE
  pixels-amphi/pixels-amphi/pom.xml
  pixels-cli/pom.xml
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/Main.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/LoadExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/load/Parameters.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/load/PixelsConsumer.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/EncodingLevel.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DecimalColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DoubleColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/FloatColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongDecimalColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/BitUtils.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/LongDecimalColumnVector.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/BaseColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/BinaryColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/BooleanColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/ByteColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/CharColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/ColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/DateColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/DecimalColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/DoubleColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/FloatColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/IntegerColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/LongDecimalColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/StringColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/TimeColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/TimestampColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/VarbinaryColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/VarcharColumnWriter.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/TestParams.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestPixelsWriter.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestStringColumnWriter.java
  pixels-daemon/pom.xml
  pixels-example/src/main/java/io/pixelsdb/pixels/example/core/TestPixelsWriter.java
  pixels-executor/src/test/java/io/pixelsdb/pixels/executor/aggregation/TestAggregator.java
  pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestPartitioner.java
  pixels-executor/src/test/java/io/pixelsdb/pixels/executor/predicate/TestPredicate.java
  pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/WorkerCommon.java
  proto/pixels.proto
Labels: bug, enhancement

#562 [Issue #556] fix time type and timestamp type
  pixels-amphi/pixels-amphi/src/main/java/io/pixelsdb/pixels/amphi/downloader/PeerDownloader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/StatsRecorder.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/TimeStatsRecorder.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/TimestampStatsRecorder.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/DatetimeUtils.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/Decimal.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/LongDecimal.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DateColumnVector.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DecimalColumnVector.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/LongDecimalColumnVector.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/TimeColumnVector.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/TimestampColumnVector.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/ColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/IntegerColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/TimeColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/TimestampColumnWriter.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/utils/TestDateTimeUtils.java
Labels: bug, enhancement

#563 [Issue #538] fix load command and docs
  docs/TPC-H.md
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/Main.java
Labels: bug, documentation

#568 [Issue #548] support endianness in bit compact and decompact
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/BooleanColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DateColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DecimalColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DoubleColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/FloatColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/IntegerColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongDecimalColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimeColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/BitUtils.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/BaseColumnWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/BooleanColumnWriter.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/encoding/TestEncoding.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/utils/TestBitUtils.java
Labels: enhancement

#569 [Issue #548] support alignment for isNull bitmap
  pixels-common/src/main/resources/pixels.properties
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriter.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/BaseColumnWriter.java
  proto/pixels.proto
Labels: enhancement
