Repository pixelsdb/pixels, pull requests merged in 2024-06, with the labels that each got.

#668 [Issue #658] add files related metadata RPCs
  README.md
  pixels-common/src/main/java/io/pixelsdb/pixels/common/error/ErrorCode.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataService.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/domain/File.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServiceImpl.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/DaoFactory.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/FileDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbFileDao.java
  pixels-daemon/src/main/resources/pixels_metadata.mwb
  pixels-storage/pixels-storage-localfs/src/main/java/io/pixelsdb/pixels/storage/localfs/LocalFS.java
  proto/metadata.proto
  scripts/sql/metadata_schema.sql
Labels: enhancement

#669 [Issue #82] fix javax.annotation dependency in pixels-retina
  pixels-retina/pom.xml
Labels: bug

#670 [Issue #82] fix the build block in pixels-retina pom
  pixels-retina/pom.xml
Labels: enhancement

#664 [Issue #666] http serialization functionality
  pixels-common/pom.xml
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/HttpServer.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/HttpServerHandler.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/HttpServerInitializer.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/HttpServerUtil.java
  pixels-core/pom.xml
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderStreamImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterStreamImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderStreamImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/BlockingMap.java
  pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/WorkerCommon.java
  pixels-turbo/pixels-worker-vhive/pom.xml
  pixels-turbo/pixels-worker-vhive/src/main/java/io/pixelsdb/pixels/worker/vhive/StreamWorkerCommon.java
  pixels-turbo/pixels-worker-vhive/src/test/java/TestHttpServerClient.java
  pom.xml
  proto/stream.proto
Labels: enhancement

#671 [Issue #666] revise naming and comments for streaming format.
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderStreamImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterStreamImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderStreamImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/BlockingMap.java
  proto/stream.proto
Labels: enhancement

#676 [Issue #658] remove redundant log
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/heartbeat/HeartbeatWorker.java
Labels: documentation

#682 [Issue #681] fix output file order in common scan worker
  pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/Output.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/input/ScanInput.java
  pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BaseScanWorker.java
Labels: bug

#683 [Issue #658] add import command and automatically add files in load and compact commands
  docs/CLICKBENCH.md
  docs/TPC-H.md
  pixels-amphi/src/main/java/io/pixelsdb/pixels/amphi/coordinator/Coordinator.java
  pixels-amphi/src/main/java/io/pixelsdb/pixels/amphi/downloader/DownloadProcess.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/Main.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/CompactExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/CopyExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/FileMetaExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/ImportExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/LoadExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/StatExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/load/Parameters.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/load/PixelsConsumer.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataService.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/domain/File.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/compactor/PixelsCompactor.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServiceImpl.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/FileDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbFileDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbLayoutDao.java
  pixels-daemon/src/main/resources/pixels_metadata.mwb
  proto/metadata.proto
  scripts/sql/metadata_schema.sql
Labels: enhancement

#685 [Issue #684] support print file metadata
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheUtil.java
  pixels-cli/pom.xml
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/CompactExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/CopyExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/FileMetaExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/ImportExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/LoadExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/QueryExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/StatExecutor.java
  pixels-cli/src/test/java/io/pixelsdb/pixels/cli/TestPrintProtobuf.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/domain/OriginProjectionPattern.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Status.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderStreamImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsVersion.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterStreamImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/compactor/PixelsCompactor.java
Labels: enhancement

#686 [Issue #658] get file paths from metadata instead of storage
  pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/ProjectionPattern.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/domain/Layout.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/domain/OriginProjectionPattern.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/domain/Path.java
  pixels-common/src/test/java/io/pixelsdb/pixels/common/layout/TestProjections.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServiceImpl.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbLayoutDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbPathDao.java
  pixels-daemon/src/main/resources/pixels_metadata.mwb
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/PixelsPlanner.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/StarlingPlanner.java
  proto/metadata.proto
  scripts/sql/metadata_schema.sql
Labels: enhancement
