Repository pixelsdb/pixels, pull requests merged in 2024-05, with the labels that each got.

#648 [docs] add introduction for pixels-rover
  README.md
Labels: documentation

#650 [pixels-server] can not get vm costs for some queries (pixelsdb#649)
  pixels-common/src/main/java/io/pixelsdb/pixels/common/server/rest/response/GetQueryResultResponse.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/QueryCost.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/QueryCostType.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransService.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/transaction/TransServiceImpl.java
  pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryManager.java
  proto/transaction.proto
Labels: bug

#652 [Issue #649] clean query results periodically and fix bugs in query manager
  pixels-common/src/main/java/io/pixelsdb/pixels/common/error/ErrorCode.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/server/rest/response/GetQueryResultResponse.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransService.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/DaemonMain.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/transaction/TransServiceImpl.java
  pixels-server/src/main/java/io/pixelsdb/pixels/server/constant/ControllerParameters.java
  pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryController.java
  pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryManager.java
  pixels-server/src/test/java/io/pixelsdb/pixels/server/TestQueryAPI.java
  proto/transaction.proto
Labels: bug, enhancement

#654 [Issue #653] fix hosts for file locations
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Location.java
  pixels-common/src/test/java/io/pixelsdb/pixels/common/TestRandom.java
Labels: bug

#655 [Issue #580] reformat code and add license header
  pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/VectorColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/VectorColumnStats.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/VectorStatsRecorder.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/VectorColumnWriter.java
Labels: documentation

#662 [docs] add pixelsdb demo paper
  README.md
Labels: documentation
