Repository pixelsdb/pixels, pull requests merged in 2024-09, with the labels that each got.

#697 [Issue #698] export enviroment variables
  pixels-turbo/pixels-scaling-ec2/src/main/scripts/launch-script.sh
Labels: bug

#699 [docs] add pixelsdb vision paper
  README.md
Labels: documentation

#702 [Issue #700] getting layout while getting table
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataService.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/domain/Layout.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/domain/Table.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServiceImpl.java
  proto/metadata.proto
Labels: enhancement

#705 [Issue #704] fix create view
  pixels-daemon/src/main/resources/pixels_metadata.mwb
  scripts/sql/metadata_schema.sql
Labels: bug

#706 [Issue #647] fix sum aggregation with long decimal intermediate results
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/Integer128.java
  pixels-executor/src/main/java/io/pixelsdb/pixels/executor/aggregation/function/DecimalSum.java
  pixels-executor/src/main/java/io/pixelsdb/pixels/executor/aggregation/function/FunctionFactory.java
Labels: bug

#709 [Issue #708] remove the file id generated by etcd
  pixels-amphi/src/main/java/io/pixelsdb/pixels/amphi/downloader/DownloadProcess.java
  pixels-amphi/src/test/java/io/pixelsdb/pixels/amphi/TestMetadataService.java
  pixels-amphi/src/test/java/io/pixelsdb/pixels/amphi/analyzer/TestPlanAnalysis.java
  pixels-amphi/src/test/java/io/pixelsdb/pixels/amphi/coordinator/TestCoordinator.java
  pixels-amphi/src/test/java/io/pixelsdb/pixels/amphi/downloader/TestPeerDownloader.java
  pixels-cache/README.md
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheConfig.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/CompactExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/ImportExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/LoadExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/StatExecutor.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/error/ErrorCode.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataService.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/StorageFactory.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/server/HostPort.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
  pixels-common/src/test/java/io/pixelsdb/pixels/common/TestMetadataService.java
  pixels-common/src/test/java/io/pixelsdb/pixels/common/layout/TestCostBasedSplitsIndex.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/compactor/TestPixelsCompactor.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestPixelsWriter.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheWorker.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServiceImpl.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/FileDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/PathDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbFileDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbPathDao.java
  pixels-daemon/src/main/resources/pixels_metadata.mwb
  pixels-parser/src/test/java/io/pixelsdb/pixels/parser/TestPixelsParser.java
  pixels-parser/src/test/java/io/pixelsdb/pixels/parser/TestPixelsSchema.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/PixelsPlanner.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/StarlingPlanner.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/PlanOptimizer.java
  pixels-retina/src/main/java/io/pixelsdb/pixels/retina/RetinaWriter.java
  pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/MetadataController.java
  pixels-server/src/main/java/io/pixelsdb/pixels/server/grpc/AmphiServiceImpl.java
  pixels-storage/pixels-storage-gcs/pom.xml
  pixels-storage/pixels-storage-gcs/src/main/java/io/pixelsdb/pixels/storage/gcs/GCS.java
  pixels-storage/pixels-storage-hdfs/src/main/java/io/pixelsdb/pixels/storage/hdfs/HDFS.java
  pixels-storage/pixels-storage-localfs/pom.xml
  pixels-storage/pixels-storage-localfs/src/main/java/io/pixelsdb/pixels/storage/localfs/LocalFS.java
  pixels-storage/pixels-storage-redis/pom.xml
  pixels-storage/pixels-storage-redis/src/main/java/io/pixelsdb/pixels/storage/redis/Redis.java
  pixels-storage/pixels-storage-s3/pom.xml
  pixels-storage/pixels-storage-s3/src/main/java/io/pixelsdb/pixels/storage/s3/AbstractS3.java
  pixels-storage/pixels-storage-s3/src/main/java/io/pixelsdb/pixels/storage/s3/Minio.java
  pixels-storage/pixels-storage-s3/src/main/java/io/pixelsdb/pixels/storage/s3/S3.java
  proto/metadata.proto
  scripts/sbin/reset-cache.sh
  scripts/sql/metadata_schema.sql
Labels: enhancement

#711 [Issue #710] using seperate jvm configuration files for pixels coordinator and worker
  docs/INSTALL.md
  scripts/bin/coordinator-jvm.config
  scripts/bin/run-class.sh
  scripts/bin/worker-jvm.config
Labels: enhancement

#712 [Issue #710] fix seperate jvm configurations for pixels coordinator and worker
  scripts/bin/run-class.sh
Labels: bug

#714 [Issue #713] fix unable to cache layout version 0
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheUtil.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheWorker.java
Labels: bug

#719 [Issue #715] fix get file id bug
  pixels-core/src/main/java/io/pixelsdb/pixels/core/compactor/PixelsCompactor.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/heartbeat/HeartbeatCoordinator.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/heartbeat/HeartbeatWorker.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbPathDao.java
Labels: bug

#721 [Issue #715] revise trans and metadata services
  pixels-amphi/src/test/java/io/pixelsdb/pixels/amphi/TestMetadataService.java
  pixels-amphi/src/test/java/io/pixelsdb/pixels/amphi/analyzer/TestPlanAnalysis.java
  pixels-amphi/src/test/java/io/pixelsdb/pixels/amphi/coordinator/TestCoordinator.java
  pixels-amphi/src/test/java/io/pixelsdb/pixels/amphi/downloader/TestPeerDownloader.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/CacheLocationDistribution.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/AbsoluteBalancer.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/Balancer.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/ReplicaBalancer.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataService.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/server/HostAddress.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransService.java
  pixels-common/src/test/java/io/pixelsdb/pixels/common/TestBalancer.java
  pixels-common/src/test/java/io/pixelsdb/pixels/common/TestMetadataService.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/compactor/TestPixelsCompactor.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestPixelsWriter.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
  pixels-parser/src/test/java/io/pixelsdb/pixels/parser/TestPixelsParser.java
  pixels-parser/src/test/java/io/pixelsdb/pixels/parser/TestPixelsSchema.java
  pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryManager.java
Labels: bug, enhancement

#722 [Issue #715] fix the worker hostnames in the cache plan
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheWorker.java
Labels: bug

#727 [Issue #724] update configurations and docs for pixels-cache
  docs/INSTALL.md
  pixels-cache/README.md
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheConfig.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
  pixels-cache/src/test/java/io/pixelsdb/pixels/cache/BenchmarkCacheIndexReader.java
  pixels-cache/src/test/java/io/pixelsdb/pixels/cache/BenchmarkCacheReader.java
  pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPartitionCacheReader.java
  pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPartitionCacheWriter.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/AbsoluteBalancer.java
  pixels-common/src/main/resources/pixels.properties
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/heartbeat/HeartbeatConfig.java
  scripts/bin/start-vmtouch.sh
  scripts/bin/stop-vmtouch.sh
Labels: documentation, enhancement

#728 [Issue #636] remove cache schema and table from config file and fix memory leak in cache writer
  pixels-cache/README.md
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheConfig.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheUtil.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsPhysicalReader.java
  pixels-cache/src/test/java/io/pixelsdb/pixels/cache/BenchmarkCacheIndexReader.java
  pixels-cache/src/test/java/io/pixelsdb/pixels/cache/BenchmarkCacheReader.java
  pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPartitionCacheReader.java
  pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPartitionCacheWriter.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/SchemaTableName.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
  pixels-common/src/main/resources/pixels.properties
  pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestPixelsWriter.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheWorker.java
  scripts/sbin/reset-cache.sh
Labels: bug, enhancement
