Repository pixelsdb/pixels, pull requests merged in 2024-10, with the labels that each got.

#763 [Issue #736] fix typos
  pixels-common/src/main/java/io/pixelsdb/pixels/common/task/Worker.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/WorkerCoordinateServiceImpl.java
Labels: documentation

#765 [pixels-retine] clean proto files
  cpp/pixels-amphi-worker/README.md
  cpp/pixels-retina/README.md
  cpp/pixels-retina/include/retina_writer_client.h
  cpp/pixels-retina/proto/retina_service.proto
  cpp/pixels-retina/proto/retina_writer.proto
  cpp/pixels-retina/src/CMakeLists.txt
  cpp/pixels-retina/src/retina_client.cc
  cpp/pixels-retina/src/retina_server.cc
  cpp/pixels-retina/tests/CMakeLists.txt
  pixels-retina/src/main/java/io/pixelsdb/pixels/retina/RetinaService.java
  pixels-retina/src/main/java/io/pixelsdb/pixels/retina/RetinaWriterServer.java
  proto/retina.proto
  proto/retina_service.proto
  proto/retina_writer.proto
Labels: documentation, enhancement

#754 [Issue #737] implement hidden timestamp column
  pixels-amphi/src/main/java/io/pixelsdb/pixels/amphi/downloader/PeerDownloader.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/CompactExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/LoadExecutor.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/load/Parameters.java
  pixels-cli/src/main/java/io/pixelsdb/pixels/cli/load/PixelsConsumer.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/Input.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/compactor/PixelsCompactor.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/BinaryColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/BooleanColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ByteColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DateColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DecimalColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DoubleColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/FloatColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/IntegerColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongDecimalColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsReaderOption.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimeColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/VectorColumnReader.java
  pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/BitUtils.java
  pixels-core/src/test/java/io/pixelsdb/pixels/core/utils/TestBitUtils.java
  pixels-example/src/main/java/io/pixelsdb/pixels/example/core/TestColumnReader.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/PixelsPlanner.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/StarlingPlanner.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/input/AggregationInput.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/input/BroadcastChainJoinInput.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/input/BroadcastJoinInput.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/input/JoinInput.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/input/PartitionInput.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/input/PartitionedChainJoinInput.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/input/PartitionedJoinInput.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/input/ScanInput.java
  pixels-planner/src/test/java/io/pixelsdb/pixels/planner/TestPixelsPlanner.java
  pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BaseAggregationWorker.java
  pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BaseBroadcastChainJoinWorker.java
  pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BaseBroadcastJoinWorker.java
  pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BasePartitionStreamWorker.java
  pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BasePartitionWorker.java
  pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BasePartitionedChainJoinWorker.java
  pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BasePartitionedJoinWorker.java
  pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BaseScanStreamWorker.java
  pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BaseScanWorker.java
  pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/WorkerCommon.java
  pixels-turbo/pixels-worker-vhive/src/test/java/TestConverter.java
  proto/pixels.proto
Labels: enhancement
