Repository pixelsdb/pixels, pull requests merged in 2025-07, with the labels that each got.

#929 [Issue #928] Wrap interfaces with RetinaService and fix some bugs in WriterBuffer
  pixels-common/src/main/java/io/pixelsdb/pixels/common/retina/RetinaService.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/retina/RetinaServerImpl.java
  pixels-retina/src/main/java/io/pixelsdb/pixels/retina/PixelsWriterBuffer.java
  scripts/etc/retina-jvm.config
Labels: bug, enhancement

#950 [Issue #949] check and fix code problems after rebasing master
  pixels-common/src/main/java/io/pixelsdb/pixels/common/sink/SinkProvider.java
  pixels-retina/src/main/java/io/pixelsdb/pixels/retina/RetinaService.java
Labels: enhancement

#952 [Issue #949] add missing spike worker names into pixels.properties
  pixels-common/src/main/resources/pixels.properties
Labels: enhancement

#969 [Issue #916] update index service interface, index docs, and the rockset Jni code structure.
  README.md
  cpp/pixels-index/pixels-index-rockset/CMakeLists.txt
  cpp/pixels-index/pixels-index-rockset/README.md
  cpp/pixels-index/pixels-index-rockset/include/RocksetJni.h
  cpp/pixels-index/pixels-index-rockset/lib/RocksetJni.cpp
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/IndexService.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/MainIndex.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/MainIndexImpl.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/SinglePointIndex.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/SinglePointIndexFactory.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/sink/SinkProvider.java
  pixels-common/src/main/resources/pixels.properties
  pixels-common/src/test/java/io/pixelsdb/pixels/common/index/MainIndexImplTest.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/DaemonMain.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/index/IndexServer.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/index/IndexServiceImpl.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/sink/SinkServer.java
  pixels-index/pixels-index-rocksdb/README.md
  pixels-index/pixels-index-rocksdb/src/main/java/io/pixelsdb/pixels/index/rocksdb/RocksDBIndex.java
  pixels-index/pixels-index-rockset/README.md
  pixels-index/pixels-index-rockset/src/main/java/io/pixelsdb/pixels/index/rocksdb/RocksetIndex.java
  pixels-index/pixels-index-rockset/src/test/java/io/pixelsdb/pixels/index/rocksdb/RocksetTest.java
  pixels-index/pixels-index-rockset/src/test/java/io/pixelsdb/pixels/index/rocksdb/TestRocksetIndex.java
  proto/index.proto
Labels: documentation, enhancement

#970 [Issue #916] fix compilation problem caused by index service interface changes
  pixels-index/pixels-index-rocksdb/src/main/java/io/pixelsdb/pixels/index/rocksdb/RocksDBIndex.java
  pixels-index/pixels-index-rocksdb/src/test/java/io/pixelsdb/pixels/index/rocksdb/TestRocksDBIndex.java
  pixels-index/pixels-index-rockset/src/main/java/io/pixelsdb/pixels/index/rocksdb/RocksetIndex.java
Labels: bug

#963 [Issue #957] Implement a multi-zone non-blocking caching framework with online cache scaling capabilities
  pixels-cache/README.md
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/CacheScalingOperation.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsBucketToZoneMap.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsBucketTypeInfo.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheConfig.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheReader.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheUtil.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsHasher.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsLocator.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsMurmurHasher.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsZoneReader.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsZoneUtil.java
  pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsZoneWriter.java
  pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPixelsCacheReader.java
  pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPixelsCacheWriter.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/MemoryMappedFile.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheWorker.java
Labels: enhancement

#976 [Issue #916] implement open/close/remove/flush index in index service
  pixels-common/src/main/java/io/pixelsdb/pixels/common/error/ErrorCode.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/IndexService.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/MainIndex.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/MainIndexFactory.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/SinglePointIndex.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/SinglePointIndexFactory.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/index/IndexServiceImpl.java
  pixels-index/pixels-index-main-sqlite/pom.xml
  pixels-index/pixels-index-main-sqlite/src/main/java/io/pixelsdb/pixels/index/main/sqlite/SqliteMainIndex.java
  pixels-index/pixels-index-main-sqlite/src/main/java/io/pixelsdb/pixels/index/main/sqlite/SqliteMainIndexProvider.java
  pixels-index/pixels-index-rocksdb/pom.xml
  pixels-index/pixels-index-rocksdb/src/main/java/io/pixelsdb/pixels/index/rocksdb/RocksDBIndex.java
  pixels-index/pixels-index-rocksdb/src/main/java/io/pixelsdb/pixels/index/rocksdb/RocksDBIndexProvider.java
  pixels-index/pixels-index-rocksdb/src/test/java/io/pixelsdb/pixels/index/rocksdb/TestRocksDBIndex.java
  pixels-index/pixels-index-rockset/pom.xml
  pixels-index/pixels-index-rockset/src/main/java/io/pixelsdb/pixels/index/rockset/CloudDBOptions.java
  pixels-index/pixels-index-rockset/src/main/java/io/pixelsdb/pixels/index/rockset/RocksetIndex.java
  pixels-index/pixels-index-rockset/src/main/java/io/pixelsdb/pixels/index/rockset/RocksetIndexProvider.java
  pixels-index/pixels-index-rockset/src/main/resources/META-INF/services/io.pixelsdb.pixels.common.index.SinglePointIndexProvider
  pixels-index/pixels-index-rockset/src/test/java/io/pixelsdb/pixels/index/rockset/TestRocksetIndex.java
  proto/index.proto
Labels: enhancement

#981 [Issue #916] revise index service interface and add purge index
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/IndexService.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/index/IndexServiceImpl.java
  proto/index.proto
Labels: bug, enhancement
