Repository pixelsdb/pixels, pull requests merged in 2025-10, with the labels that each got.

#1084 [Issue #1083] Return ByteBuffer directly for read-only buffers from S3 Reader
  pixels-retina/src/main/java/io/pixelsdb/pixels/retina/FileWriterManager.java
  pixels-retina/src/main/java/io/pixelsdb/pixels/retina/MinioManager.java
Labels: bug

#1089 [Issue #1088] revise dependencies and fix conflicting netty and grpc versions
  pixels-amphi/pom.xml
  pixels-cache/pom.xml
  pixels-cli/pom.xml
  pixels-common/pom.xml
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/EtcdUtil.java
  pixels-core/pom.xml
  pixels-daemon/pom.xml
  pixels-example/pom.xml
  pixels-executor/pom.xml
  pixels-index/pixels-index-main-sqlite/pom.xml
  pixels-index/pixels-index-main-sqlite/src/main/java/io/pixelsdb/pixels/index/main/sqlite/SqliteMainIndex.java
  pixels-index/pixels-index-rocksdb/pom.xml
  pixels-index/pixels-index-rocksdb/src/main/java/io/pixelsdb/pixels/index/rocksdb/RocksDBFactory.java
  pixels-index/pixels-index-rocksdb/src/main/java/io/pixelsdb/pixels/index/rocksdb/RocksDBIndex.java
  pixels-index/pixels-index-rockset/pom.xml
  pixels-index/pixels-index-rockset/src/main/java/io/pixelsdb/pixels/index/rockset/RocksetIndex.java
  pixels-index/pixels-index-rockset/src/main/java/io/pixelsdb/pixels/index/rockset/RocksetIndexStub.java
  pixels-parser/pom.xml
  pixels-planner/pom.xml
  pixels-retina/pom.xml
  pixels-server/pom.xml
  pixels-storage/pixels-storage-gcs/pom.xml
  pixels-storage/pixels-storage-hdfs/pom.xml
  pixels-storage/pixels-storage-http/pom.xml
  pixels-storage/pixels-storage-http/src/test/java/io/pixelsdb/pixels/storage/http/TestHttpStream.java
  pixels-storage/pixels-storage-localfs/pom.xml
  pixels-storage/pixels-storage-mock/pom.xml
  pixels-storage/pixels-storage-redis/pom.xml
  pixels-storage/pixels-storage-s3/pom.xml
  pixels-storage/pixels-storage-s3qs/pom.xml
  pixels-turbo/pixels-invoker-lambda/pom.xml
  pixels-turbo/pixels-invoker-spike/pom.xml
  pixels-turbo/pixels-invoker-vhive/pom.xml
  pixels-turbo/pixels-scaling-ec2/pom.xml
  pixels-turbo/pixels-scaling-general/pom.xml
  pixels-turbo/pixels-worker-common/pom.xml
  pixels-turbo/pixels-worker-lambda/pom.xml
  pixels-turbo/pixels-worker-spike/pom.xml
  pixels-turbo/pixels-worker-vhive/pom.xml
  pom.xml
Labels: bug, dependencies

#1093 [Issue #1092] fix log4j dependency for httpclient
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/HttpUtil.java
  pixels-retina/pom.xml
  pixels-storage/pixels-storage-s3/pom.xml
  pom.xml
Labels: enhancement

#1098 [Issue #1097] adjust ports for pixels services
  pixels-common/src/main/resources/pixels.properties
  pixels-server/README.md
  pixels-server/pom.xml
  pixels-server/src/main/resources/application.properties
Labels: bug

#1100 [Issue #1094] resolve conflicting log libraries
  pixels-amphi/README.md
  pixels-amphi/pom.xml
  pixels-amphi/src/main/java/io/pixelsdb/pixels/amphi/downloader/DownloadProcess.java
  pixels-cli/pom.xml
  pixels-daemon/pom.xml
  pixels-parser/pom.xml
  pixels-server/pom.xml
  pixels-server/src/main/resources/templates/login.html
  pixels-turbo/pixels-worker-vhive/pom.xml
  pom.xml
Labels: bug

#1102 [Issue #1094] avoid inheriting log4j-slf4j-impl dependency from storage-s3 to other modules
  pixels-amphi/src/main/java/io/pixelsdb/pixels/amphi/coordinator/Coordinator.java
  pixels-server/pom.xml
  pixels-storage/pixels-storage-s3/pom.xml
Labels: bug

#1112 [Issue #1105] prevent concurrent instantiation of singletons in Java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/MainIndexFactory.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/SinglePointIndexFactory.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/IndexFactory.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataCache.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataService.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/SchedulerFactory.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/StorageFactory.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/NoopScheduler.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/RateLimitedScheduler.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/SortMergeScheduler.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/retina/RetinaService.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransContext.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransContextCache.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransService.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/InvokerFactory.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/ConfigFactory.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/EtcdUtil.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/GcMonitor.java
  pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/MetaDBUtil.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/DaoFactory.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbFileDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbLayoutDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbPathDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbPeerDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbPeerPathDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbRangeDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbRangeIndexDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbSchemaDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbSchemaVersionDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbSinglePointIndexDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbTableDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbViewDao.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/transaction/TransContextManager.java
  pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/transaction/TransServiceImpl.java
  pixels-executor/src/main/java/io/pixelsdb/pixels/executor/aggregation/function/FunctionFactory.java
  pixels-index/pixels-index-rocksdb/src/main/java/io/pixelsdb/pixels/index/rocksdb/RocksDBFactory.java
  pixels-parser/src/main/java/io/pixelsdb/pixels/parser/PixelsParser.java
  pixels-parser/src/main/java/io/pixelsdb/pixels/parser/PixelsSchemaFactory.java
  pixels-parser/src/main/java/io/pixelsdb/pixels/parser/PixelsTable.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/CFWorkerManager.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/PlanCoordinatorFactory.java
  pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/PlanOptimizer.java
  pixels-retina/src/main/java/io/pixelsdb/pixels/retina/MinioManager.java
  pixels-retina/src/main/java/io/pixelsdb/pixels/retina/RetinaResourceManager.java
  pixels-turbo/pixels-invoker-lambda/src/main/java/io/pixelsdb/pixels/invoker/lambda/Lambda.java
  pixels-turbo/pixels-invoker-spike/src/main/java/io/pixelsdb/pixels/invoker/spike/SpikeAsyncClient.java
  pixels-turbo/pixels-invoker-spike/src/main/java/io/pixelsdb/pixels/invoker/spike/SpikeInvoker.java
  pixels-turbo/pixels-invoker-vhive/src/main/java/io/pixelsdb/pixels/invoker/vhive/ScanInvoker.java
  pixels-turbo/pixels-invoker-vhive/src/main/java/io/pixelsdb/pixels/invoker/vhive/Vhive.java
  pixels-turbo/pixels-scaling-ec2/src/main/java/io/pixelsdb/pixels/scaling/ec2/CloudWatch.java
  pixels-turbo/pixels-worker-vhive/src/main/java/io/pixelsdb/pixels/worker/vhive/Main.java
  pixels-turbo/pixels-worker-vhive/src/main/java/io/pixelsdb/pixels/worker/vhive/utils/ServiceImpl.java
Labels: bug

#1117 [Issue #1115] using HashMap and post-sorting in MainIndexBuffer for better performance
  pixels-common/src/main/java/io/pixelsdb/pixels/common/index/MainIndexBuffer.java
  pixels-common/src/test/java/io/pixelsdb/pixels/common/index/LocalIndexServiceTest.java
  pixels-index/pixels-index-main-sqlite/src/main/java/io/pixelsdb/pixels/index/main/sqlite/SqliteMainIndex.java
  pixels-index/pixels-index-main-sqlite/src/test/java/io/pixelsdb/pixels/index/main/sqlite/TestSqliteMainIndex.java
Labels: enhancement
